{{- if and (eq .Values.internalDatabase.enabled true) (eq .Values.internalDatabase.persistence.enabled true) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "leantime.fullname" . }}-db
spec:
  accessModes:
    - {{ .Values.internalDatabase.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.internalDatabase.persistence.size | quote }}
  {{- if .Values.internalDatabase.persistence.storageClass }}
  storageClassName: {{ .Values.internalDatabase.persistence.storageClass | quote }}
  {{- end }}
{{- end -}}