{{- $database := "" }}
{{- if and (eq .Values.internalDatabase.enabled true) (not .Values.internalDatabase.existingSecret) }}
  {{- $database = "internal" }}
{{- else if and (eq .Values.externalDatabase.enabled true) (not .Values.externalDatabase.existingSecret )}}
  {{- $database = "external" }}
{{- end -}}

{{- $s3 := "" }}
{{- if and (eq .Values.leantime.s3.enabled true) (not .Values.leantime.s3.existingSecret) }}
{{- $s3 = required "Key required to enable S3" .Values.leantime.s3.key | b64enc | quote }}
{{- end -}}

{{- $smtpUser := "" }}
{{- if and (eq .Values.leantime.smtp.enabled true ) (not .Values.leantime.smtp.existingSecret) (eq .Values.leantime.smtp.auth true) }}
{{- $smtpUser = required "User required to enable SMTP" .Values.leantime.smtp.user | b64enc | quote }}
{{- end -}}

{{- $oidcClientId := "" }}
{{- if and (eq .Values.leantime.oidc.enabled true ) (not .Values.leantime.oidc.existingSecret) }}
{{- $oidcClientId = required "Client ID required to enable OIDC" .Values.leantime.oidc.clientId | b64enc | quote }}
{{- end -}}

{{- $sessionSalt := "" }}
{{- if not .Values.leantime.existingSecret }}
{{- $sessionSalt = .Values.leantime.sessionSalt | default (randAlphaNum 32) | b64enc | quote }}
{{- end -}}

{{- $redisPassword := "" }}
{{- if and (eq .Values.leantime.redis.enabled true) (not .Values.leantime.redis.url) (not .Values.leantime.redis.existingSecret) .Values.leantime.redis.password }}
{{- $redisPassword = .Values.leantime.redis.password | quote }}
{{- end -}}

{{- if or (ne $database "") (ne $s3 "") (ne $smtpUser "" ) (ne $sessionSalt "") (ne $redisPassword "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leantime.fullname" . }}
  labels:
    {{- include "leantime.labels" . | nindent 4 }}
data:
  {{- if ne $database "" }}
  {{- if eq $database "internal" }}
  database-root: {{ .Values.internalDatabase.rootPassword | default (randAlphaNum 24) | b64enc | quote }}
  database-user: {{ .Values.internalDatabase.user | b64enc | quote }}
  database-password: {{ .Values.internalDatabase.password | default (randAlphaNum 24) | b64enc | quote }}
  {{- else }}
  database-user: {{ required "User required for external database" .Values.externalDatabase.user | b64enc | quote }}
  database-password: {{ required "Password required for external database" .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if ne $s3 "" }}
  s3-key: {{ $s3 }}
  s3-secret: {{ required "Secret required to enable S3" .Values.leantime.s3.secret | b64enc | quote }}
  {{- end }}
  {{- if ne $smtpUser "" }}
  smtp-user: {{ $smtpUser }}
  smtp-password: {{ required "Must specify SMTP password" .Values.leantime.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if ne $oidcClientId "" }}
  oidc-client-id: {{ $oidcClientId }}
  oidc-client-secret: {{ required "Client Secret required to enable OIDC" .Values.leantime.oidc.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if ne $sessionSalt "" }}
  session-salt: {{ $sessionSalt }}
  {{- end }}
  {{- if ne $redisPassword "" }}
  redis-password: {{ $redisPassword }}
  {{- end }}
{{- end }}