{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bitwardenrs.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "bitwardenrs.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ required "Host required for ingress" .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.bitwardenrs.enableWebsockets }}
          - path: "/notifications/hub"
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.websocketPort }}
          {{- end }}
          - path: "/"
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.httpPort }}
{{- end }}
